using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace DAI.Exception
{
    public enum ExceptionTypes
    {
        SEHException = 1,
        ArgumentOutOfRangeException = 2,
        ArgumentNullException = 3,
        DivideByZeroException = 4,
        NotFiniteNumberException = 5,
        OverflowException = 6,
        FileNotFoundException = 7,
        PathTooLongException = 8,
        ExternalException = 9,
        ArgumentException = 10,
        InvalidOperationException = 11,
        AccessViolationException = 12,
        NullReferenceException = 13,
        IndexOutOfRangeException = 14,
        ArithmeticException = 15,
        ArrayTypeMismatchException = 16,
        IOException = 17,
        FormatException = 18,
        InvalidCastException = 19,
        MulticastNotSupportedException = 20,
        NotImplementedException = 21,
        NotSupportedException = 22,
        OutOfMemoryException = 23,
        SecurityException = 24,
        InvalidUdtException = 25,
        ValidationException = 26,
        AppDomainUnloadedException = 27,
        BadImageFormatException = 28,
        CannotUnloadAppDomainException = 29,
        KeyNotFoundException = 30,
        LicenseException = 31,
        WarningException = 32,
        ConfigurationException = 33,
        InstallException = 34,
        ContextMarshalException = 35,
        DataException = 36,
        DBConcurrencyException = 37,
        OperationAbortedException = 38,
        SqlTypeException = 39,
        DataMisalignedException = 40,
        DeploymentException = 41,
        PrincipalException = 42,
        InvalidPrinterException = 43,
        RegistrationException = 44,
        ServicedComponentException = 45,
        ExecutionEngineException = 46,
        InsufficientExecutionStackException = 47,
        InvalidProgramException = 48,
        InternalBufferOverflowException = 49,
        InvalidDataException = 50,
        MemberAccessException = 51,
        OperationCanceledException = 52,
        RankException = 53,
        AmbiguousMatchException = 54,
        ReflectionTypeLoadException = 55,
        MissingManifestResourceException = 56,
        MissingSatelliteAssemblyException = 57,
        SerializationException = 58,
        AuthenticationException = 59,
        CryptographicException = 60,
        HostProtectionException = 61,
        PolicyException = 62,
        IdentityNotMappedException = 63,
        VerificationException = 64,
        XmlSyntaxException = 65,
        CommunicationException = 66,
        InvalidBodyAccessException = 67,
        MultipleFilterMatchesException = 68,
        ServiceProcessTimeoutException = 69,
        QuotaExceededException = 70,
        AbandonedMutexException = 71,
        SemaphoreFullException = 72,
        SynchronizationLockException = 73,
        ThreadAbortException = 74,
        ThreadInterruptedException = 75,
        ThreadStartException = 76,
        ThreadStateException = 77,
        TimeoutException = 78,
        TypeInitializationException = 79,
        TypeLoadException = 80,
        TypeUnloadedException = 81,
        UnauthorizedAccessException = 82,
        UriTemplateMatchException = 83,
        DatabaseNotEnabledForNotificationException = 84,
        TableNotEnabledForNotificationException = 85,
        SqlExecutionException = 86,
        SoapException = 87,
        XmlSchemaException = 88,
        XmlException = 89,
        XPathException = 90,
        XsltException = 91,
        SystemException = 92,
        Exception = 93
    }
}
